### PR TITLE
Working on more attributes

### PR DESCRIPTION
**Pull request by owenrumney**

### CODE REVIEW

**Comment by kiwiz** [comment]
👋 I need a couple of the new fields in some code I'm working on. Anything I can help with for getting a new version pushed out?

**Comment by owenrumney** [comment]
Hey @kiwiz  - are the attributes you need in this PR? Still only interested in parsing rather than generating. I can release this if so

**Comment by kiwiz** [comment]
Yup, just interested in parsing. :]

**Comment by kiwiz** [comment]
Whoo, thanks! 🎉

**Pull request merged**
